server:
  port: 8082

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://119.8.61.8:6033/security-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true

#  mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/zhou/mapper/*.xml
  type-aliases-package: com.zhou.entity
logging:
  level:
    com.zhou: debug